import "./assets/main.css";
import "primevue/resources/themes/md-dark-deeppurple/theme.css";
import "primeflex/primeflex.css";

import "primevue/resources/primevue.min.css"; /* Deprecated */
import "primeicons/primeicons.css";
// import router from "./router";
import { createApp } from "vue";
// import { createApp } from 'vue';
import PrimeVue from "primevue/config";
import Ripple from "primevue/ripple";
import TabMenu from "primevue/tabmenu";
import Menubar from "primevue/menubar";
import Avatar from "primevue/avatar";
import InputText from "primevue/inputtext";
import Dropdown from "primevue/dropdown";
import App from "./App.vue";
import router from "./router";
import Card from "primevue/card";
import PanelMenu from "primevue/panelmenu";
import Toast from "primevue/toast";
import store from "./store";
import Panel from "primevue/panel";
import Listbox from "primevue/listbox";
import Button from "primevue/button";
import Image from "primevue/image";
import InputGroup from "primevue/inputgroup";
import InputGroupAddon from "primevue/inputgroupaddon";
import FloatLabel from "primevue/floatlabel";
import InputMask from "primevue/inputmask";
import Badge from "primevue/badge";
import AccordionTab from "primevue/accordiontab";
import Accordion from "primevue/accordion";
import ProgressBar from "primevue/progressbar";
import FileUpload from "primevue/fileupload";
import Editor from "primevue/editor";
import Password from "primevue/password";
import InlineMessage from "primevue/inlinemessage";
import ToastService from "primevue/toastservice";
import Textarea from "primevue/textarea";
// import Toast from "primevue/toast";
const app = createApp(App);
import { validate } from "vee-validate";
import ProgressSpinner from "primevue/progressspinner";
import Dialog from "primevue/dialog";
import Tooltip from "primevue/tooltip";

app.directive("tooltip", Tooltip);
// import VeeValidate from "vee-validate";

app.use(validate);
app.use(router);
app.use(store);
app.component("Menubar", Menubar);
app.component("Avatar", Avatar);
app.component("InputText", InputText);
app.component("TabMenu", TabMenu);
app.component("Dropdown", Dropdown);
app.component("Textarea", Textarea);
app.component("Card", Card);
app.component("PanelMenu", PanelMenu);
app.component("Toast", Toast);
app.component("Listbox", Listbox);
app.component("Button", Button);
app.component("Image", Image);
app.component("InputGroup", InputGroup);
app.component("Tooltip", Tooltip);
app.directive("tooltip", Tooltip);
app.component("InputGroupAddon", InputGroupAddon);
app.component("FloatLabel", FloatLabel);
app.component("InputMask", InputMask);
app.component("AccordionTab", AccordionTab);
app.component("Accordion", Accordion);
app.component("Dialog", Dialog);
app.component("ProgressBar", ProgressBar);
app.component("FileUpload", FileUpload);
app.component("Password", Password);
app.component("Editor", Editor);
app.component("Badge", Badge);
app.component("InlineMessage", InlineMessage);
app.component("ProgressSpinner", ProgressSpinner);
app.directive("ripple", Ripple);
app.use(PrimeVue);
app.use(ToastService);
app.mount("#app");
